//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoSM.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESTAURANTE
    {
        public int cCodRest { get; set; }
        public string cNombre { get; set; }
        public string cDireccion { get; set; }
        public string cContacto { get; set; }
        public Nullable<decimal> cLatitud { get; set; }
        public Nullable<decimal> cLongitud { get; set; }
        public Nullable<bool> cParking { get; set; }
        public Nullable<bool> cInternet { get; set; }
        public Nullable<bool> cVisa { get; set; }
        public Nullable<bool> cMastercard { get; set; }
        public Nullable<decimal> cValoracion { get; set; }
        public Nullable<int> cCodTipo { get; set; }
        public Nullable<int> cCodDescuento { get; set; }
        public string cTelefono { get; set; }
        public string cCelular { get; set; }
        public string cHorario { get; set; }
    }
}
